<dl>
        <dd>
          <h3><a href="[field:arcurl/]" class="title">[field:title/]</a> </h3>
          <p><b>导语：</b>[field:description/]...<a href="/jcsb/42.html">[详细]</a></p>
          <span> <a href="/swt/" rel="nofollow" target="_blank"><img src="/templets/wuhan/images/list_1.jpg" width="116px" height="31px"></a> <a href="/swt/" rel="nofollow" target="_blank"><img src="/templets/wuhan/images/list_2.jpg" width="116px" height="31px"></a> </span> 
        </dd>
      </dl>