<dl>
        <dd>
          <h3><a href="[field:arcurl/]" class="title">[field:title/]</a> </h3>
          <p><b>导语：</b>在对甲状腺功能进行检查时，经常会看到抗甲状腺球蛋白偏高，但是很多患者对这专业术语不是很了解。那么这是什么意思呢？ 描述病情，免费帮你一对一分析 抗甲状腺球蛋白抗体(...<a href="/jcsb/42.html">[详细]</a></p>
          <span> <a href="/swt/" rel="nofollow" target="_blank"><img src="{dede:global.cfg_templets_skin/}/images/list_1.jpg" width="116px" height="31px"></a> <a href="/swt/" rel="nofollow" target="_blank"><img src="{dede:global.cfg_templets_skin/}/images/list_2.jpg" width="116px" height="31px"></a> </span> 
        </dd>
      </dl>