
<field:user itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:user>


<field:pwd itemname="性别" autofield="1" type="radio" isnull="true" default="男,女"  maxlength="250" page="">
</field:pwd>


<field:age itemname="年龄" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:age>

<field:tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>
