<?php
$z[0]=Array("global","",42,74);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("field","",131,159);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",161,190);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n        <li><a href=\"[field:typelink/]\" rel=\"nofollow\">[field:typename/]</a></li>\r\n        ",245,392);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";
$z[4]=Array("arclist","\r\n        <h3><a href=\"[field:arcurl/]\">[field:title /]</a></h3>\r\n        <p><span>导读：</span>饮食不当是导致甲亢的因素之一，科学饮食能够起到有效预防甲亢的作…<a href=\"[field:arcurl/]\"><详情></a></p>\r\n        ",427,734);
$z[4][4]=array();
$z[4][4]['titlelen']="36";
$z[4][4]['row']="1";
$z[4][4]['flag']="h";
$z[5]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\"><span>>></span>[field:title /]</a> </li>\r\n        ",779,931);
$z[5][4]=array();
$z[5][4]['titlelen']="50";
$z[5][4]['row']="5";
$z[5][4]['flag']="c";

?>