<?php
$z[0]=Array("global","",32,64);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",1134,1166);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1301,1333);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1481,1513);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("channel","\r\n    <li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n  ",1839,1955);
$z[4][4]=array();
$z[4][4]['typeid']="3";
$z[4][4]['row']="5";

?>