<?php
$z[0]=Array("global","",31,63);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",1110,1142);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1274,1306);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1452,1484);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("channel","\n    <li><a href='[field:typelink/]'>[field:typename/]</a></li>\n  ",1795,1909);
$z[4][4]=array();
$z[4][4]['typeid']="3";
$z[4][4]['row']="5";

?>