<?php
$z[0]=Array("global","",34,66);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",142,169);
$z[1][4]=array();
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("channel","\r\n    <span>|</span></li>\r\n    <li><a href=\"[field:typelink/]\">[field:typename/]</a>\r\n  ",191,330);
$z[2][4]=array();
$z[2][4]['row']="4";
$z[2][4]['type']="top";
$z[3]=Array("global","",936,968);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1102,1134);
$z[4][4]=array();
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1282,1314);
$z[5][4]=array();
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("channel","\r\n    <li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n  ",1638,1754);
$z[6][4]=array();
$z[6][4]['typeid']="3";
$z[6][4]['row']="5";

?>