<?php
$z[0]=Array("global","",423,449);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",502,532);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",569,596);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1639,1676);
$z[3][4]=array();
$z[3][4]['filename']="head_m.htm";
$z[4]=Array("channel","\r\n                <a href=\"[field:typelink/]\" >\r\n                    <li class=\"li00[field:id/]\">\r\n                        <i></i>\r\n                        <p>[field:typename/]</p>\r\n                    </li>\r\n                </a>\r\n            ",2446,2737);
$z[4][4]=array();
$z[4][4]['typeid']="3";
$z[4][4]['row']="5";
$z[5]=Array("include","",8674,8713);
$z[5][4]=array();
$z[5][4]['filename']="footer_m.htm";

?>