<?php
$z[0]=Array("global","",414,440);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",492,522);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",558,585);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1612,1649);
$z[3][4]=array();
$z[3][4]['filename']="head_m.htm";
$z[4]=Array("channel","\n                <a href=\"[field:typelink/]\" >\n                    <li class=\"li00[field:id/]\">\n                        <i></i>\n                        <p>[field:typename/]</p>\n                    </li>\n                </a>\n            ",2403,2687);
$z[4][4]=array();
$z[4][4]['typeid']="3";
$z[4][4]['row']="5";
$z[5]=Array("include","",8239,8278);
$z[5][4]=array();
$z[5][4]['filename']="footer_m.htm";

?>