<?php
$z[0]=Array("field","",415,434);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",435,461);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",501,530);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",569,628);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1671,1708);
$z[4][4]=array();
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("field","",1937,1960);
$z[5][4]=array();
$z[5][4]['name']="seotitle";
$z[6]=Array("list","  \n    <div class=\"nr\">\n		<!-- <a href=\"view.php?aid=[field:id/]\"> -->\n		<a href=\"[field:arcurl/]\">\n		<div class=\"nr_l fl\">\n            <div class=\"tit\">[field:title/]</div>\n            <img src=\"/assets/images/arc_hot.gif\">\n		</div>\n		<div class=\"nr_r fr\"><span><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" style=\"color:#fff; background:#064A9E; padding:2px 4px;\">在线咨询</a></span></div>\n		</a>\n		<div class=\"clear\"></div>\n      </div>\n	",2248,2779);
$z[6][4]=array();
$z[6][4]['pagesize']="8";
$z[6][4]['titlelen']="40";
$z[7]=Array("pagelist","",2838,2905);
$z[7][4]=array();
$z[7][4]['listitem']="info,index,pre,next,option";
$z[7][4]['listsize']="1";
$z[8]=Array("include","",5860,5899);
$z[8][4]=array();
$z[8][4]['filename']="footer_m.htm";

?>