<?php
$z[0]=Array("global","",735,767);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\"><span>>></span>[field:title/]</a></li>\r\n        ",1418,1590);
$z[1][4]=array();
$z[1][4]['typeid']="";
$z[1][4]['row']="10";
$z[1][4]['col']="1";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="";
$z[2]=Array("global","",1751,1783);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";

?>